//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PeruTourism.ws_SendGridEmail {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsMailsSoap", Namespace="http://tempuri.org/")]
    public partial class wsMails : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnviarCorreoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsMails() {
            this.Url = global::PeruTourism.Properties.Settings.Default.PeruTourism_ws_SendGridEmail_wsMails;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnviarCorreoCompletedEventHandler EnviarCorreoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta EnviarCorreo(Autenticacion credenciales, Correo informacion) {
            object[] results = this.Invoke("EnviarCorreo", new object[] {
                        credenciales,
                        informacion});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarCorreoAsync(Autenticacion credenciales, Correo informacion) {
            this.EnviarCorreoAsync(credenciales, informacion, null);
        }
        
        /// <remarks/>
        public void EnviarCorreoAsync(Autenticacion credenciales, Correo informacion, object userState) {
            if ((this.EnviarCorreoOperationCompleted == null)) {
                this.EnviarCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarCorreoOperationCompleted);
            }
            this.InvokeAsync("EnviarCorreo", new object[] {
                        credenciales,
                        informacion}, this.EnviarCorreoOperationCompleted, userState);
        }
        
        private void OnEnviarCorreoOperationCompleted(object arg) {
            if ((this.EnviarCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarCorreoCompleted(this, new EnviarCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Autenticacion {
        
        private TipoWeb inWebIdField;
        
        private string stUsuarioField;
        
        private string stClaveField;
        
        /// <remarks/>
        public TipoWeb InWebId {
            get {
                return this.inWebIdField;
            }
            set {
                this.inWebIdField = value;
            }
        }
        
        /// <remarks/>
        public string StUsuario {
            get {
                return this.stUsuarioField;
            }
            set {
                this.stUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string StClave {
            get {
                return this.stClaveField;
            }
            set {
                this.stClaveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TipoWeb {
        
        /// <remarks/>
        Mozart,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Respuesta {
        
        private TipoRespuesta tipoField;
        
        private string valorField;
        
        private string otroValorField;
        
        /// <remarks/>
        public TipoRespuesta Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string OtroValor {
            get {
                return this.otroValorField;
            }
            set {
                this.otroValorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TipoRespuesta {
        
        /// <remarks/>
        Exito,
        
        /// <remarks/>
        Alerta,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Adjunto {
        
        private string archivoBytesField;
        
        private string nombreArchivoField;
        
        /// <remarks/>
        public string ArchivoBytes {
            get {
                return this.archivoBytesField;
            }
            set {
                this.archivoBytesField = value;
            }
        }
        
        /// <remarks/>
        public string NombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Correo {
        
        private string nombreEmisorField;
        
        private string correoEmisorField;
        
        private string destinatariosField;
        
        private string asuntoField;
        
        private string cuerpoTextoField;
        
        private string cuerpoHtmlField;
        
        private Adjunto[] adjuntosField;
        
        /// <remarks/>
        public string NombreEmisor {
            get {
                return this.nombreEmisorField;
            }
            set {
                this.nombreEmisorField = value;
            }
        }
        
        /// <remarks/>
        public string CorreoEmisor {
            get {
                return this.correoEmisorField;
            }
            set {
                this.correoEmisorField = value;
            }
        }
        
        /// <remarks/>
        public string Destinatarios {
            get {
                return this.destinatariosField;
            }
            set {
                this.destinatariosField = value;
            }
        }
        
        /// <remarks/>
        public string Asunto {
            get {
                return this.asuntoField;
            }
            set {
                this.asuntoField = value;
            }
        }
        
        /// <remarks/>
        public string CuerpoTexto {
            get {
                return this.cuerpoTextoField;
            }
            set {
                this.cuerpoTextoField = value;
            }
        }
        
        /// <remarks/>
        public string CuerpoHtml {
            get {
                return this.cuerpoHtmlField;
            }
            set {
                this.cuerpoHtmlField = value;
            }
        }
        
        /// <remarks/>
        public Adjunto[] Adjuntos {
            get {
                return this.adjuntosField;
            }
            set {
                this.adjuntosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EnviarCorreoCompletedEventHandler(object sender, EnviarCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591